site_name: SDM Documentation
repo_url: https://github.com/Sensa-Data/sensa-docs
site_url: https://docs.sensadata.io
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png 
  features:
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - navigation.footer
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
  language: en
  palette:
    - scheme: default
      primary: deep orange
      accent: deep orange 
    

plugins:
  - social
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Sensa-Data

markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true

copyright: |
  &copy; 2023 <a href="https://github.com/Sensa-Data"  target="_blank" rel="noopener">Sensa Data</a>

nav:
  - SensaDataMesh:
      - Introduction to SDM: README.md
      - Getting started:
          - Ingest data : examples/ingest.md
          - Read data: examples/read.md
          