site_name: SDM Documentation
theme:
   name: material
site_url: https://docs.sensadata.io
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png 
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: indigo
      accent: lime

plugins:
  - social

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Sensa-Data

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2023 <a href="https://github.com/Sensa-Data"  target="_blank" rel="noopener">Sensa Data</a>